import './globals.css';

export const metadata = {
  title: '💱 Currency Converter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='container'>
          {children}
        </div>
      </body>
    </html>
  )
}
