import { Header } from '../components/Header';
import PropTypes from 'prop-types';
import styles from './page.module.css';
import './globals.css';

export const metadata = {
  title: 'Currency Converter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel='icon' href='/favicon.ico'/>
      </head>
      <body>
        <div className={styles.container}>
          <Header />
          <main className={styles.main}>{children}</main>
        </div>
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node,
};
